# Generated by Django 5.0 on 2023-12-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Our',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('title_1', models.CharField(max_length=255, verbose_name='Заголовок - 1')),
                ('discriptions_1', models.TextField(verbose_name='Описание - 1')),
                ('title_2', models.CharField(max_length=255, verbose_name='Описание - 2')),
                ('discriptions_2', models.TextField(verbose_name='Заголовок - 2')),
                ('botton', models.CharField(max_length=50, verbose_name='Кнопка')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О насс',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя:')),
                ('discriptions', models.TextField(verbose_name='Описание:')),
                ('info', models.CharField(max_length=255, verbose_name='Кнопка:')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото:')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
    ]
