# Generated by Django 5.0 on 2023-12-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_field', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='our',
            name='discriptions_3',
            field=models.TextField(default=1, verbose_name='Заголовок - 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our',
            name='title_3',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание - 3'),
            preserve_default=False,
        ),
    ]
