# Generated by Django 5.0 on 2023-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_about_us_delete_our'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(upload_to='user_image', verbose_name='ваше фото'),
        ),
    ]
