# Generated by Django 5.0 on 2023-12-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_about_us_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
