# Generated by Django 5.0 on 2023-12-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_delete_yourmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='discriptions_1',
            field=models.TextField(verbose_name='Первое описание'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='discriptions_2',
            field=models.TextField(verbose_name='Второе описание'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='discriptions_3',
            field=models.TextField(verbose_name='Третее описание'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_1',
            field=models.CharField(max_length=255, verbose_name='Первый заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_2',
            field=models.CharField(max_length=255, verbose_name='Второй заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_3',
            field=models.CharField(max_length=255, verbose_name='Третий заголовок'),
        ),
    ]
