# Generated by Django 5.0 on 2023-12-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('mini_description', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='personal_userimage', verbose_name='Фотография')),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
