# Generated by Django 5.0 on 2023-12-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_personalinformation_delete_yourmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name': 'Ваша информация', 'verbose_name_plural': 'Личная информация'},
        ),
    ]
