# Generated by Django 5.0 on 2023-12-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_personalinformation_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='facebook',
            field=models.URLField(default=1, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='inn',
            field=models.URLField(default=1, verbose_name='In'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='instagramm',
            field=models.URLField(default=1, verbose_name='Инстаграм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='skype',
            field=models.URLField(default=1, verbose_name='skype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='you_tube',
            field=models.URLField(default=1, verbose_name='You Tube'),
            preserve_default=False,
        ),
    ]
