# Generated by Django 5.0 on 2023-12-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_mainpage_delete_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
