# Generated by Django 5.0 on 2023-12-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_servis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servis',
            options={'verbose_name': 'Наши сервисы', 'verbose_name_plural': 'Наш сервис'},
        ),
    ]
