# Generated by Django 5.0 on 2023-12-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_remove_servis_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='user_photo', verbose_name='Фото клиента')),
                ('reviews', models.TextField(max_length=255, verbose_name='Отзыв')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('profession', models.CharField(max_length=255, verbose_name='Професия')),
                ('back_photo', models.ImageField(upload_to='back_photo', verbose_name='Фото заднего фона')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзыв',
            },
        ),
    ]
