# Generated by Django 5.0 on 2023-12-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='back_photo',
        ),
    ]
