# Generated by Django 5.0 on 2023-12-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_remove_reviews_back_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='partfolio_user_image', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Портфолии',
                'verbose_name_plural': 'Портфолия',
            },
        ),
    ]
