# Generated by Django 5.0 on 2023-12-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_partfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Балл')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Крутые факты',
                'verbose_name_plural': 'Крутой факт',
            },
        ),
    ]
