# Generated by Django 5.0 on 2023-12-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя-фамилия')),
                ('profession', models.CharField(max_length=255, verbose_name='Професия')),
                ('image', models.ImageField(upload_to='uorteam_user_image', verbose_name='Фотография')),
                ('facebook', models.URLField(verbose_name='URL-Фейсбук')),
                ('twitter', models.URLField(verbose_name='URL-Твиттер')),
                ('google', models.URLField(verbose_name='URL-Google+')),
            ],
            options={
                'verbose_name': 'Наши команды',
                'verbose_name_plural': 'Наша команда',
            },
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='facebook',
            field=models.URLField(verbose_name='URL-Facebook'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='inn',
            field=models.URLField(verbose_name='URL-In'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='instagramm',
            field=models.URLField(verbose_name='URL-Инстаграм'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='skype',
            field=models.URLField(verbose_name='URL-skype'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='twitter',
            field=models.URLField(verbose_name='URL-Твиттер'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='you_tube',
            field=models.URLField(verbose_name='URL-You Tube'),
        ),
    ]
