# Generated by Django 5.0 on 2023-12-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='blogpost_image', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Blog-публикации',
                'verbose_name_plural': 'Blog-публикация',
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Cвязаться с нами', 'verbose_name_plural': 'Обратная связ'},
        ),
    ]
