# Generated by Django 5.0 on 2023-12-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Загруза видео'},
        ),
    ]
