# Generated by Django 5.0 on 2023-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_infocontacts_alter_partfolio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocontacts',
            name='descriptions_1',
            field=models.TextField(verbose_name='Расписание рабочего дня'),
        ),
    ]
