# Generated by Django 5.0 on 2023-12-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_alter_infocontacts_descriptions_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocontacts',
            name='descriptions111',
            field=models.CharField(default=1, max_length=255, verbose_name='Расписание рабочего дня'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocontacts',
            name='descriptions1111',
            field=models.CharField(default=1, max_length=255, verbose_name='Расписание рабочего дня'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocontacts',
            name='descriptions222',
            field=models.CharField(default=1, max_length=255, verbose_name='Контактная информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocontacts',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='email.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocontacts',
            name='url',
            field=models.URLField(default=1, verbose_name='URL-почты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infocontacts',
            name='descriptions_1',
            field=models.CharField(max_length=255, verbose_name='Расписание рабочего дня'),
        ),
        migrations.AlterField(
            model_name='infocontacts',
            name='descriptions_2',
            field=models.CharField(max_length=255, verbose_name='Контактная информация'),
        ),
    ]
