# Generated by Django 5.0 on 2023-12-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_infocontacts_descriptions111_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255, verbose_name='Не-много о компании')),
                ('razrab', models.URLField(verbose_name='Сылка для разработчика')),
                ('name_razrab', models.CharField(max_length=255, verbose_name='Имя разработчика')),
                ('twitter', models.URLField(verbose_name='URL-для твиттера')),
                ('facebook', models.URLField(verbose_name='URL-для фейсбука')),
                ('google', models.URLField(verbose_name='URL-для гугла')),
                ('skype', models.URLField(verbose_name='URL-для skype')),
                ('instagram', models.URLField(verbose_name='URL-для инстаграмма')),
                ('inn', models.URLField(verbose_name='URL-для Linkedin')),
                ('you_tube', models.URLField(verbose_name='URL-для You Tube')),
            ],
            options={
                'verbose_name': 'Ass',
                'verbose_name_plural': 'Ass',
            },
        ),
    ]
