# Generated by Django 5.0 on 2023-12-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_ass'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo_home', verbose_name='Логотип')),
            ],
        ),
    ]
