# Generated by Django 5.0 on 2023-12-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_homelogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homelogo',
            options={'verbose_name': 'Логотипы', 'verbose_name_plural': 'Логотип'},
        ),
    ]
